name: Node Module Version
description: setup the correct version for node-modules
runs:
  using: 'composite'
  steps:
    - name: Setup NX globally by cli version
      id: setup-nx-globally
      run: |
        npm install -g nx@$(grep -E '"@nrwl/cli":' package.json | sed -E 's/.*: "([^"]+)".*/\1/')
      shell: bash
