name: Build all services

on:
  workflow_dispatch:

jobs:
  run-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Node Version
        uses: ./.github/actions/common/versions

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Fetch secrets from AWS SSM Parameter Store
        id: fetchSecrets
        uses: maorgoldberg/aws-params-action@main
        with:
          names: /Actions/BuildNum
          withDecryption: true
        
      - name: print-output-build-number
        run: echo "build number is ${{ steps.fetchSecrets.outputs['/Actions/BuildNum'] }}"
