name: Build all services

on:
  workflow_dispatch:

jobs:
  run-dev:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Node Version
        uses: ./.github/actions/common/versions

      - name: build number
        id: build-number
        uses: ./.github/actions/build-number
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      
      - name: print-output-build-number
        run: echo "build number is ${{ steps.build-number.outputs.build-number }}"
